### PR TITLE
bump ajv version

### PR DESCRIPTION
**Pull request by epoberezkin**
Sorry for bothering you again. It's the fastest now (approx. 25% faster than imjv). It's probably the last one. Thank you.

### CODE REVIEW

**Comment by ebdrup** [comment]
I'm doing Open Open Source for this benchmark. So I added you as collaborator. Anybody who contributes valuable work, becomes a collaborator. Please continue to do pull requests. But collaborators can merge pull requests. and if there is anything controversial about them, we can talk about it in the pull request.

**Comment by epoberezkin** [comment]
Thanks! Would you like me to run it myself and merge with results?

**Comment by ebdrup** [comment]
I already ran it :-)

**Comment by epoberezkin** [comment]
Ah, yes you did :) Strange though, that's how the chart looks for me - https://chart.googleapis.com/chart?chxt=x,y&cht=bhs&chco=76A4FB&chls=2.0&chbh=26,4,1&chs=600x410&chxl=-1:|ajv|is-my-json-valid|jsen|schemasaurus|themis|jsck|z-schema|jjv|skeemas|request-validator|jsonschema|tv4|jayschema&chd=t:100,77,70.9,24.4,21.4,8.6,6.6,5.7,1,0.5,0.5,0.2,0.1

That's why I didn't notice.

**Comment by ebdrup** [comment]
For me there seems to be some difference depending on what kind of computer I run the benchmark on. I'm thinking that the CPU and it's 1st/2nd-level cache size has an impact.

**Comment by epoberezkin** [comment]
Yes, I've noticed you have different numbers - this was the slow one. Also the node version seems to make some impact. On 0.12 I'm getting even bigger difference: https://chart.googleapis.com/chart?chxt=x,y&cht=bhs&chco=76A4FB&chls=2.0&chbh=26,4,1&chs=600x410&chxl=-1:|ajv|jsen|is-my-json-valid|schemasaurus|themis|z-schema|jjv|jsck|jsonschema|skeemas|request-validator|tv4|jayschema&chd=t:100,63.4,59.7,17.3,12.2,6.3,3.8,2.6,0.6,0.6,0.4,0.2,0.1

**Pull request merged**
