### PR TITLE
update ajv validator

### PR DESCRIPTION
**Pull request by GerryFerdinandus**
Update to the never V8 version.
draft|AJV V6.12.6 test failures|AJV V8.5.0 test failures
------------|---------|---------
draft-04|26|3
draft-06|10|2
draft-07|103|35

### CODE REVIEW

**Comment by GerryFerdinandus** [comment]
Do not merge. This need to be improved. The code inside AJV setup it too big, must be init one time, for speed improvement.

**Comment by Eomm** [comment]
Should not the `package-lock` file be updated?

https://github.com/ebdrup/json-schema-benchmark/blob/e9c884f9edd38438a150fef0e9a2a1173c0fcc50/package-lock.json#L417

I cloned the repo and run the installation with npm 7 and it installed the `ajv@6` module version

**Comment by GerryFerdinandus** [comment]
@Eomm 
https://github.com/ebdrup/json-schema-benchmark/blob/e9c884f9edd38438a150fef0e9a2a1173c0fcc50/package.json#L40-L43
after git clone:
`npm run update`
This will also update AJV to the latest version

But the test will not run because AJV 8 API is change.
Need to update the AJV test code with this PR
But the AJV test is slower. No longer number one. So there may be a problem with my PR that needs to be improved.

**Comment by GerryFerdinandus** [comment]
Close this PR so that other can create better PR

**Pull request closed without merging**
