### PR TITLE
updated validator versions, added versions to README

### PR DESCRIPTION
**Pull request by epoberezkin**
I changed versions of validators to ''latest" in package.json and added version to README.template so that actual version is included in the report.
Version of JSON-Schema-Test-Suite is update to latest.
Ran the benchmark on node 0.12

### CODE REVIEW

**Comment by epoberezkin** [comment]
I've merged it, please let me know if there is any issue. Thanks

**Comment by ebdrup** [comment]
looks good. I was thinking at one point, that maybe we could schedule a nightly run on the benchmarks somehow?

**Comment by epoberezkin** [comment]
I was thinking about travis too actually. It can publish the results to somewhere...

**Comment by epoberezkin** [comment]
Or to GitHub pages like here: http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/

**Pull request merged**
