### PR TITLE
Missing link to tv4 repo added

### PR DESCRIPTION
**Pull request by Nonemoticoner**

### CODE REVIEW

**Comment by ebdrup** [comment]
The readme.md file is actually generated when th benchmark is run and should not be edited.^
These links are fetched with `npm` and the reason the link for tv4 is missing is because they have not published the module correctly to npm. 
To fix this, it's better to do a PR to tv4 and have them publish the module correctly.

**Comment by Nonemoticoner** [comment]
@ebdrup Yea, sorry, I noticed it a moment ago.

**Comment by ebdrup** [comment]
No problem :-)

**Comment by ebdrup** [comment]
I've tried to make everything auto-update automatically when the benchmark is run. So updating/adding modules should be minimal manual work.

**Comment by ebdrup** [comment]
The code could use some cleanup, but it works :-)

**Comment by Nonemoticoner** [comment]
It's weird though, because tv4's [package.json](https://github.com/geraintluff/tv4/blob/master/package.json) doesn't seem unusual and the NPM website shows the link (https://www.npmjs.com/package/tv4) to the repo.

**Comment by ebdrup** [comment]
that is weird...

**Comment by epoberezkin** [comment]
That's because the code uses `homepage` property and tv4 doesn't have it.

**Comment by epoberezkin** [comment]
And `repository.url` shouldn't be used really as it can be `git` protocol rather than https and there may be no web page to show there (even if it is https)

**Comment by ebdrup** [comment]
I'm thinking if `npm docs tv4` can use that url then we can too. Maybe add it as fallback if `homepage` is not defined?...

**Pull request closed without merging**
